### ISSUE TITLE
errors .... fava show <budget_balance_check> On-budget accounts and budget total do not match: 	

### ISSUE THREAD

**Issue by ouyanmao** [scauligi/refried#11]
Hello, according to the prompt of your project, I have successfully installed your plugin, but unfortunately the project reported an error .
Can I provide my ledger files so you can troubleshoot errors?
the web fava(ver.1.19，beancount ver.2.3.4) show errors like this:

```bean
option "operating_currency" "USD"

plugin "refried.plugins.rebudget"                                   
2022-06-01 custom "fava-extension" "refried.extensions.avail_ext" 

; plugin "refried.plugins.clearing"
; 2020-01-01 custom "fava-extension" "refried.extensions.accts_ext"
; 2020-01-01 custom "fava-extension" "refried.extensions.journal_ext"

2022-06-01 open Assets:Cash
  ordering: 
  ; autoclear: TRUE 
2022-06-01 open Expenses:Obligations:Rent
  ordering: 7
  ; autoclear: TRUE
2022-06-01 open Expenses:Obligations:Utilities
  ordering: 6   
  ; autoclear: TRUE
2022-06-01 open Expenses:Necessities:Groceries
  ordering: 3
  ; autoclear: TRUE
2022-06-01 open Expenses:Fun-money:Video-games
  ordering: 4 
  ; autoclear: TRUE

2022-06-01 open Equity:Opening-Balances

2022-06-01 open Liabilities:Payable:VISA

2022-06-01 open Income:To-be-budgeted

; When I insert this transaction, fava reports an error： On-budget accounts and budget total do not match:(29802.00 USD) vs (-198 USD)
; 2022-06-01 * "begin my ledger"
;   Assets:Cash                                      30000.00 USD
;   Equity:Opening-Balances                         -30000.00 USD

```

Thanks sir!

**Comment by scauligi** [comment]
Ah shoot sorry it took me so long to get to this.
The `rebudget` plugin enforces that your sum total of money (Assets+Liabilities) matches the amount of money you've budgeted (to Income+Expenses), since Every Dollar Needs a Job™.

You can fix this by replacing `Equity:Opening-Balances` with `Income:To-be-budgeted` in your initial transaction.

Alternatively, if you want to keep the initial transaction as balanced against Equity, you can fix the error by adding a second budgeting transaction to reflect the new money:

```
2022-06-01 * "begin my budget"
  Equity:Opening-Balances                          30000.00 USD
  Income:To-be-budgeted                           -30000.00 USD
```

Note that the `rebudget` plugin will automatically attach the `#rebudget` tag to this transaction, since it's purely a budgeting transaction; this way, for your reports, you can always filter with `-#rebudget` to get the "classic" view of your ledger.

**Comment by vkbytes** [comment]
I still see the error even after adding
```
2022-06-01 * "begin my budget"
  Equity:Opening-Balances                          30000.00 USD
  Income:To-be-budgeted                           -30000.00 USD
```
`The amounts what I have in the file. Do We have to add "to be budgeted" for every Asset Opening balances?
